# This is the image we are going add micromaba to:
FROM violafanfani/tcga-data-base-r:0.0.4

USER root

RUN ping -c 4 google.com

# adding opencontainer labels to link registry to github repository
LABEL org.opencontainers.image.title="tcga-data-nf"
LABEL org.opencontainers.image.description="Workflow to download and prepare TCGA data"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/violafanfani/tcga-data-nf"
LABEL org.opencontainers.image.documentation="https://github.com/QuackenbushLab/tcga-data-nf"
LABEL org.opencontainers.image.source="https://github.com/QuackenbushLab/tcga-data-nf"
LABEL org.opencontainers.image.vendor="https://github.com/QuackenbushLab"
LABEL org.opencontainers.image.authors="Viola Fanfani"
LABEL org.opencontainers.image.revision="v0.0.13"

RUN apt-get update && apt-get install -y ca-certificates

RUN python3 -m pip install --upgrade pip

###
RUN apt-get update


RUN R -e "devtools::install_github('pmandros/TCGAPurityFiltering')"
RUN R -e "devtools::install_github('immunogenomics/presto')"
RUN R -e "devtools::install_github('aet21/EpiSCORE')"

ADD  NetSciDataCompanion/ /opt/NetSciDataCompanion/
#RUN R -e "devtools::install_local('/opt/NetSciDataCompanion/', force=TRUE, dependencies=T)"
RUN R -e "devtools::install_github('https://github.com/QuackenbushLab/NetworkDataCompanion')"